# Generated by Django 3.2.9 on 2022-01-25 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0002_auto_20220118_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_project', related_query_name='contributor_project', to='SoftDesk.project'),
        ),
    ]
