# Generated by Django 3.2.9 on 2022-01-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0004_alter_contributor_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='role',
            field=models.CharField(default='contributor', max_length=128),
        ),
    ]
