# Generated by Django 3.2.9 on 2022-01-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0006_alter_contributor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contributors', related_query_name='project_contributors', to='SoftDesk.project'),
        ),
    ]
